Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load images
camera_calibration_images_file = '../../data/camera_calibration_*.jpg'
images_path_names = glob.glob(camera_calibration_images_file)

# Get first image
image = cv2.imread(images_path_names[0])
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(gray, cmap='gray')
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mIndexError[0m                                Traceback (most recent call last)
Cell [1;32mIn[2], line 6[0m
[0;32m      3[0m images_path_names [38;5;241m=[39m glob[38;5;241m.[39mglob(camera_calibration_images_file)
[0;32m      5[0m [38;5;66;03m# Get first image[39;00m
[1;32m----> 6[0m image [38;5;241m=[39m cv2[38;5;241m.[39mimread([43mimages_path_names[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m)
[0;32m      7[0m gray [38;5;241m=[39m cv2[38;5;241m.[39mcvtColor(image, cv2[38;5;241m.[39mCOLOR_BGR2GRAY)
[0;32m      8[0m plt[38;5;241m.[39mimshow(gray, cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mgray[39m[38;5;124m'[39m)

[1;31mIndexError[0m: list index out of range

