Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Converting RGB image to grayscale
gray = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

# Compute edges
canny = cv2.Canny(gray, 50, 200)

# Search Houghlines
lines = cv2.HoughLines(canny, 1, np.pi/180, 200)

# Run for loop through each line
for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x_1 = int(x0 + 1000 * (-b))
    y_1 = int(y0 + 1000 * (a))
    x_2 = int(x0 - 1000 * (-b))
    y_2 = int(y0 - 1000 * (a))
    cv2.line(image2, (x_1, y_1), (x_2, y_2), (255, 0, 0), 2)
    
# Show Final output
plt.imshow(image2)
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31merror[0m                                     Traceback (most recent call last)
Cell [1;32mIn[3], line 2[0m
[0;32m      1[0m [38;5;66;03m# Converting RGB image to grayscale[39;00m
[1;32m----> 2[0m gray [38;5;241m=[39m [43mcv2[49m[38;5;241;43m.[39;49m[43mcvtColor[49m[43m([49m[43mimage2[49m[43m,[49m[43m [49m[43mcv2[49m[38;5;241;43m.[39;49m[43mCOLOR_BGR2GRAY[49m[43m)[49m
[0;32m      4[0m [38;5;66;03m# Compute edges[39;00m
[0;32m      5[0m canny [38;5;241m=[39m cv2[38;5;241m.[39mCanny(gray, [38;5;241m50[39m, [38;5;241m200[39m)

[1;31merror[0m: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


