Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Preprocess the input image
transform = T.Compose([T.ToTensor()])
img_tensor = transform(img)
 
# Forward-pass the model, the input is a list, hence the output will also be a list
output = model([img_tensor])[0]
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[4], line 3[0m
[0;32m      1[0m [38;5;66;03m# Preprocess the input image[39;00m
[0;32m      2[0m transform [38;5;241m=[39m T[38;5;241m.[39mCompose([T[38;5;241m.[39mToTensor()])
[1;32m----> 3[0m img_tensor [38;5;241m=[39m [43mtransform[49m[43m([49m[43mimg[49m[43m)[49m
[0;32m      5[0m [38;5;66;03m# Forward-pass the model, the input is a list, hence the output will also be a list[39;00m
[0;32m      6[0m output [38;5;241m=[39m model([img_tensor])[[38;5;241m0[39m]

File [1;32mc:\python39\lib\site-packages\torchvision\transforms\transforms.py:95[0m, in [0;36mCompose.__call__[1;34m(self, img)[0m
[0;32m     93[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, img):
[0;32m     94[0m     [38;5;28;01mfor[39;00m t [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39mtransforms:
[1;32m---> 95[0m         img [38;5;241m=[39m [43mt[49m[43m([49m[43mimg[49m[43m)[49m
[0;32m     96[0m     [38;5;28;01mreturn[39;00m img

File [1;32mc:\python39\lib\site-packages\torchvision\transforms\transforms.py:135[0m, in [0;36mToTensor.__call__[1;34m(self, pic)[0m
[0;32m    127[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, pic):
[0;32m    128[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m    129[0m [38;5;124;03m    Args:[39;00m
[0;32m    130[0m [38;5;124;03m        pic (PIL Image or numpy.ndarray): Image to be converted to tensor.[39;00m
[1;32m   (...)[0m
[0;32m    133[0m [38;5;124;03m        Tensor: Converted image.[39;00m
[0;32m    134[0m [38;5;124;03m    """[39;00m
[1;32m--> 135[0m     [38;5;28;01mreturn[39;00m [43mF[49m[38;5;241;43m.[39;49m[43mto_tensor[49m[43m([49m[43mpic[49m[43m)[49m

File [1;32mc:\python39\lib\site-packages\torchvision\transforms\functional.py:121[0m, in [0;36mto_tensor[1;34m(pic)[0m
[0;32m    119[0m     _log_api_usage_once(to_tensor)
[0;32m    120[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (F_pil[38;5;241m.[39m_is_pil_image(pic) [38;5;129;01mor[39;00m _is_numpy(pic)):
[1;32m--> 121[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mpic should be PIL Image or ndarray. Got [39m[38;5;132;01m{[39;00m[38;5;28mtype[39m(pic)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[0;32m    123[0m [38;5;28;01mif[39;00m _is_numpy(pic) [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m _is_numpy_image(pic):
[0;32m    124[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mpic should be 2/3 dimensional. Got [39m[38;5;132;01m{[39;00mpic[38;5;241m.[39mndim[38;5;132;01m}[39;00m[38;5;124m dimensions.[39m[38;5;124m"[39m)

[1;31mTypeError[0m: pic should be PIL Image or ndarray. Got <class 'NoneType'>

